-- The methods each widget type has in Forever, from Ketho/BlizzardInterfaceResources (forever,
-- 1.60.1 build 70009) Resources/WidgetAPI.lua, with the methods each type inherits. That file
-- lists Region as inheriting itself; its WidgetHierarchy.png puts Region after ScriptRegion, so
-- Region takes ScriptRegion's methods here.
-- The stand-in's widgets have only these: calling any other method fails, as in the game.
-- Made by Tests/MakeWidgetAPI.lua; to update, run it again.
return {
	Frame = {
		"AbortDrag", "AddAccessRestrictions", "AddForbiddenAspects", "AddRoleset", "AddSecretAspect",
		"AdjustPointsOffset", "CanBeAccessedInContext", "CanChangeAttribute", "CanChangeProtectedState",
		"CanPropagateMouseClicks", "CanPropagateMouseMotion", "ClearAllPoints", "ClearAlphaGradient",
		"ClearAttribute", "ClearAttributes", "ClearParentKey", "ClearPoint", "ClearPointsOffset",
		"ClearScripts", "CollapsesLayout", "CreateAnimationGroup", "CreateFontString", "CreateLine",
		"CreateMaskTexture", "CreateTexture", "CreateVectorGraphics", "DesaturateHierarchy",
		"DisableDrawLayer", "DoesClipChildren", "DoesHyperlinkPropagateToParent", "EnableDrawLayer",
		"EnableGamePadButton", "EnableGamePadStick", "EnableKeyboard", "EnableMouse",
		"EnableMouseMotion", "EnableMouseWheel", "ExecuteAttribute", "FocusEnter", "FocusExit",
		"GetAccessRestrictions", "GetAlpha", "GetAnimationGroups", "GetAttribute", "GetBottom",
		"GetBoundsRect", "GetCenter", "GetChildren", "GetClampRectInsets", "GetDebugName",
		"GetDontSavePosition", "GetEffectiveAlpha", "GetEffectiveScale",
		"GetEffectivelyFlattensRenderLayers", "GetFlattensRenderLayers", "GetForbiddenAspects",
		"GetFrameLevel", "GetFrameStrata", "GetHeight", "GetHighestFrameLevel", "GetHitRectInsets",
		"GetHyperlinksEnabled", "GetID", "GetInheritableForbiddenAspects", "GetLeft", "GetName",
		"GetNumChildren", "GetNumPoints", "GetNumRegions", "GetObjectTable", "GetObjectType",
		"GetOnUpdateMode", "GetParent", "GetParentKey", "GetPoint", "GetPointByName",
		"GetPropagateKeyboardInput", "GetRaisedFrameLevel", "GetRect", "GetRegions", "GetResizeBounds",
		"GetRight", "GetRolesetNames", "GetRoundLayoutToNearestPixel", "GetScale", "GetScaledRect",
		"GetScript", "GetSize", "GetSourceLocation", "GetTop", "GetWidth", "GetWindow",
		"HasAccessConstraints", "HasAlphaGradient", "HasAnyAccessRestrictions", "HasAnyForbiddenAspects",
		"HasAnySecretAspect", "HasFixedFrameLevel", "HasFixedFrameStrata", "HasScript",
		"HasSecretAspect", "HasSecretValues", "Hide", "HookScript", "InterceptStartDrag", "Intersects",
		"IsAnchoringRestricted", "IsAnchoringSecret", "IsClampedToScreen", "IsCollapsed", "IsDragging",
		"IsDrawLayerEnabled", "IsEventRegistered", "IsForbidden", "IsFrameBuffer",
		"IsGamePadButtonEnabled", "IsGamePadStickEnabled", "IsHighlightLocked",
		"IsIgnoringChildrenForBounds", "IsIgnoringParentAlpha", "IsIgnoringParentScale",
		"IsKeyboardEnabled", "IsMouseClickEnabled", "IsMouseEnabled", "IsMouseMotionEnabled",
		"IsMouseMotionFocus", "IsMouseOver", "IsMouseWheelEnabled", "IsMovable", "IsObjectLoaded",
		"IsObjectType", "IsPreventingSecretValues", "IsProtected", "IsRectValid", "IsResizable",
		"IsRolesetFiltered", "IsShown", "IsToplevel", "IsUserPlaced", "IsUsingParentLevel", "IsVisible",
		"LockHighlight", "Lower", "MouseDown", "MouseUp", "Raise", "RegisterAllEvents", "RegisterEvent",
		"RegisterEventCallback", "RegisterForDrag", "RegisterUnitEvent", "RegisterUnitEventCallback",
		"RemoveRoleset", "ResizeToBoundsRect", "RotateTextures", "SetAllPoints", "SetAlpha",
		"SetAlphaFromBoolean", "SetAlphaGradient", "SetAttribute", "SetAttributeNoHandler",
		"SetClampRectInsets", "SetClampedToScreen", "SetClipsChildren", "SetCollapsesLayout",
		"SetDontSavePosition", "SetDrawLayerEnabled", "SetFixedFrameLevel", "SetFixedFrameStrata",
		"SetFlattensRenderLayers", "SetForbidden", "SetFrameLevel", "SetFrameStrata", "SetHeight",
		"SetHighlightLocked", "SetHitRectInsets", "SetHyperlinkPropagateToParent",
		"SetHyperlinksEnabled", "SetID", "SetIgnoreParentAlpha", "SetIgnoreParentScale",
		"SetIgnoringChildrenForBounds", "SetIsFrameBuffer", "SetMouseClickEnabled",
		"SetMouseMotionEnabled", "SetMovable", "SetOnUpdateMode", "SetParent", "SetParentKey",
		"SetPassThroughButtons", "SetPoint", "SetPointsOffset", "SetPropagateKeyboardInput",
		"SetPropagateMouseClicks", "SetPropagateMouseMotion", "SetResizable", "SetResizeBounds",
		"SetRolesets", "SetRoundLayoutToNearestPixel", "SetScale", "SetScript", "SetShown", "SetSize",
		"SetToDefaults", "SetToplevel", "SetUserPlaced", "SetUsingParentLevel", "SetWidth", "SetWindow",
		"ShouldButtonPassThrough", "Show", "StartMoving", "StartSizing", "StopAnimating",
		"StopMovingOrSizing", "UnlockHighlight", "UnregisterAllEvents", "UnregisterEvent",
	},
	Button = {
		"AbortDrag", "AddAccessRestrictions", "AddForbiddenAspects", "AddRoleset", "AddSecretAspect",
		"AdjustPointsOffset", "CanBeAccessedInContext", "CanChangeAttribute", "CanChangeProtectedState",
		"CanPropagateMouseClicks", "CanPropagateMouseMotion", "ClearAllPoints", "ClearAlphaGradient",
		"ClearAttribute", "ClearAttributes", "ClearDisabledTexture", "ClearHighlightTexture",
		"ClearNormalTexture", "ClearParentKey", "ClearPoint", "ClearPointsOffset", "ClearPushedTexture",
		"ClearScripts", "Click", "CollapsesLayout", "CreateAnimationGroup", "CreateFontString",
		"CreateLine", "CreateMaskTexture", "CreateTexture", "CreateVectorGraphics",
		"DesaturateHierarchy", "Disable", "DisableDrawLayer", "DoesClipChildren",
		"DoesHyperlinkPropagateToParent", "Enable", "EnableDrawLayer", "EnableGamePadButton",
		"EnableGamePadStick", "EnableKeyboard", "EnableMouse", "EnableMouseMotion", "EnableMouseWheel",
		"ExecuteAttribute", "FocusEnter", "FocusExit", "GetAccessRestrictions", "GetAlpha",
		"GetAnimationGroups", "GetAttribute", "GetBottom", "GetBoundsRect", "GetButtonState",
		"GetCenter", "GetChildren", "GetClampRectInsets", "GetDebugName", "GetDisabledFontObject",
		"GetDisabledTexture", "GetDontSavePosition", "GetEffectiveAlpha", "GetEffectiveScale",
		"GetEffectivelyFlattensRenderLayers", "GetFlattensRenderLayers", "GetFontString",
		"GetForbiddenAspects", "GetFrameLevel", "GetFrameStrata", "GetHeight", "GetHighestFrameLevel",
		"GetHighlightFontObject", "GetHighlightTexture", "GetHitRectInsets", "GetHyperlinksEnabled",
		"GetID", "GetInheritableForbiddenAspects", "GetLeft", "GetMotionScriptsWhileDisabled", "GetName",
		"GetNormalFontObject", "GetNormalTexture", "GetNumChildren", "GetNumPoints", "GetNumRegions",
		"GetObjectTable", "GetObjectType", "GetOnUpdateMode", "GetParent", "GetParentKey", "GetPoint",
		"GetPointByName", "GetPropagateKeyboardInput", "GetPushedTextOffset", "GetPushedTexture",
		"GetRaisedFrameLevel", "GetRect", "GetRegions", "GetResizeBounds", "GetRight", "GetRolesetNames",
		"GetRoundLayoutToNearestPixel", "GetScale", "GetScaledRect", "GetScript", "GetSize",
		"GetSourceLocation", "GetText", "GetTextHeight", "GetTextWidth", "GetTop", "GetWidth",
		"GetWindow", "HasAccessConstraints", "HasAlphaGradient", "HasAnyAccessRestrictions",
		"HasAnyForbiddenAspects", "HasAnySecretAspect", "HasFixedFrameLevel", "HasFixedFrameStrata",
		"HasScript", "HasSecretAspect", "HasSecretValues", "Hide", "HookScript", "InterceptStartDrag",
		"Intersects", "IsAnchoringRestricted", "IsAnchoringSecret", "IsClampedToScreen", "IsCollapsed",
		"IsDragging", "IsDrawLayerEnabled", "IsEnabled", "IsEventRegistered", "IsForbidden",
		"IsFrameBuffer", "IsGamePadButtonEnabled", "IsGamePadStickEnabled", "IsHighlightLocked",
		"IsIgnoringChildrenForBounds", "IsIgnoringParentAlpha", "IsIgnoringParentScale",
		"IsKeyboardEnabled", "IsMouseClickEnabled", "IsMouseEnabled", "IsMouseMotionEnabled",
		"IsMouseMotionFocus", "IsMouseOver", "IsMouseWheelEnabled", "IsMovable", "IsObjectLoaded",
		"IsObjectType", "IsPreventingSecretValues", "IsProtected", "IsRectValid", "IsResizable",
		"IsRolesetFiltered", "IsShown", "IsToplevel", "IsUserPlaced", "IsUsingParentLevel", "IsVisible",
		"LockHighlight", "Lower", "MouseDown", "MouseUp", "Raise", "RegisterAllEvents", "RegisterEvent",
		"RegisterEventCallback", "RegisterForClicks", "RegisterForDrag", "RegisterForMouse",
		"RegisterUnitEvent", "RegisterUnitEventCallback", "RemoveRoleset", "ResizeToBoundsRect",
		"RotateTextures", "SetAllPoints", "SetAlpha", "SetAlphaFromBoolean", "SetAlphaGradient",
		"SetAttribute", "SetAttributeNoHandler", "SetButtonState", "SetClampRectInsets",
		"SetClampedToScreen", "SetClipsChildren", "SetCollapsesLayout", "SetDisabledAtlas",
		"SetDisabledFontObject", "SetDisabledTexture", "SetDontSavePosition", "SetDrawLayerEnabled",
		"SetEnabled", "SetFixedFrameLevel", "SetFixedFrameStrata", "SetFlattensRenderLayers",
		"SetFontString", "SetForbidden", "SetFormattedText", "SetFrameLevel", "SetFrameStrata",
		"SetHeight", "SetHighlightAtlas", "SetHighlightFontObject", "SetHighlightLocked",
		"SetHighlightTexture", "SetHitRectInsets", "SetHyperlinkPropagateToParent",
		"SetHyperlinksEnabled", "SetID", "SetIgnoreParentAlpha", "SetIgnoreParentScale",
		"SetIgnoringChildrenForBounds", "SetIsFrameBuffer", "SetMotionScriptsWhileDisabled",
		"SetMouseClickEnabled", "SetMouseMotionEnabled", "SetMovable", "SetNormalAtlas",
		"SetNormalFontObject", "SetNormalTexture", "SetOnUpdateMode", "SetParent", "SetParentKey",
		"SetPassThroughButtons", "SetPoint", "SetPointsOffset", "SetPropagateKeyboardInput",
		"SetPropagateMouseClicks", "SetPropagateMouseMotion", "SetPushedAtlas", "SetPushedTextOffset",
		"SetPushedTexture", "SetResizable", "SetResizeBounds", "SetRolesets",
		"SetRoundLayoutToNearestPixel", "SetScale", "SetScript", "SetShown", "SetSize", "SetText",
		"SetToDefaults", "SetToplevel", "SetUserPlaced", "SetUsingParentLevel", "SetWidth", "SetWindow",
		"ShouldButtonPassThrough", "Show", "StartMoving", "StartSizing", "StopAnimating",
		"StopMovingOrSizing", "UnlockHighlight", "UnregisterAllEvents", "UnregisterEvent",
	},
	Texture = {
		"AddAccessRestrictions", "AddForbiddenAspects", "AddMaskTexture", "AddSecretAspect",
		"AdjustPointsOffset", "CanBeAccessedInContext", "CanChangeProtectedState",
		"CanPropagateMouseClicks", "CanPropagateMouseMotion", "ClearAllPoints", "ClearParentKey",
		"ClearPoint", "ClearPointsOffset", "ClearRadialProgressBar", "ClearSVG", "ClearScripts",
		"ClearTextureSlice", "ClearVertexOffsets", "CollapsesLayout", "CreateAnimationGroup",
		"EnableMouse", "EnableMouseMotion", "EnableMouseWheel", "FocusEnter", "FocusExit",
		"GetAccessRestrictions", "GetAlpha", "GetAnimationGroups", "GetAtlas", "GetBlendMode",
		"GetBottom", "GetCenter", "GetDebugName", "GetDesaturation", "GetDrawLayer", "GetEffectiveScale",
		"GetForbiddenAspects", "GetHeight", "GetHorizTile", "GetInheritableForbiddenAspects", "GetLeft",
		"GetMaskTexture", "GetName", "GetNumMaskTextures", "GetNumPoints", "GetObjectTable",
		"GetObjectType", "GetParent", "GetParentKey", "GetPoint", "GetPointByName",
		"GetRadialProgressBarEndOffset", "GetRadialProgressBarFeather", "GetRadialProgressBarPercent",
		"GetRadialProgressBarReverse", "GetRadialProgressBarStartOffset", "GetRect", "GetRight",
		"GetRotation", "GetRoundLayoutToNearestPixel", "GetScale", "GetScaledRect", "GetScript",
		"GetSize", "GetSourceLocation", "GetTexCoord", "GetTexelSnappingBias", "GetTexture",
		"GetTextureFileID", "GetTextureFilePath", "GetTextureSliceMargins", "GetTextureSliceMode",
		"GetTop", "GetVertTile", "GetVertexColor", "GetVertexOffset", "GetWidth", "HasAccessConstraints",
		"HasAnyAccessRestrictions", "HasAnyForbiddenAspects", "HasAnySecretAspect", "HasScript",
		"HasSecretAspect", "HasSecretValues", "Hide", "HookScript", "Intersects",
		"IsAnchoringRestricted", "IsAnchoringSecret", "IsBlockingLoadRequested", "IsCollapsed",
		"IsDesaturated", "IsDragging", "IsForbidden", "IsIgnoringParentAlpha", "IsIgnoringParentScale",
		"IsMouseClickEnabled", "IsMouseEnabled", "IsMouseMotionEnabled", "IsMouseMotionFocus",
		"IsMouseOver", "IsMouseWheelEnabled", "IsObjectLoaded", "IsObjectType",
		"IsPreventingSecretValues", "IsProtected", "IsRectValid", "IsShown", "IsSnappingToPixelGrid",
		"IsVisible", "MouseDown", "MouseUp", "RemoveMaskTexture", "ResetTexCoord", "SetAllPoints",
		"SetAlpha", "SetAlphaFromBoolean", "SetAtlas", "SetBlendMode", "SetBlockingLoadsRequested",
		"SetCollapsesLayout", "SetColorTexture", "SetDesaturated", "SetDesaturation", "SetDrawLayer",
		"SetForbidden", "SetGradient", "SetHeight", "SetHorizTile", "SetIgnoreParentAlpha",
		"SetIgnoreParentScale", "SetMask", "SetMouseClickEnabled", "SetMouseMotionEnabled", "SetParent",
		"SetParentKey", "SetPassThroughButtons", "SetPoint", "SetPointsOffset",
		"SetPropagateMouseClicks", "SetPropagateMouseMotion", "SetRadialProgressBarEndOffset",
		"SetRadialProgressBarFeather", "SetRadialProgressBarPercent", "SetRadialProgressBarReverse",
		"SetRadialProgressBarStartOffset", "SetRotation", "SetRoundLayoutToNearestPixel", "SetSVG",
		"SetScale", "SetScript", "SetShown", "SetSize", "SetSnapToPixelGrid", "SetSpriteSheetCell",
		"SetTexCoord", "SetTexelSnappingBias", "SetTexture", "SetTextureSliceMargins",
		"SetTextureSliceMode", "SetToDefaults", "SetVertTile", "SetVertexColor",
		"SetVertexColorFromBoolean", "SetVertexOffset", "SetWidth", "ShouldButtonPassThrough", "Show",
		"StopAnimating",
	},
	FontString = {
		"AddAccessRestrictions", "AddForbiddenAspects", "AddSecretAspect", "AdjustPointsOffset",
		"CalculateScreenAreaFromCharacterSpan", "CanBeAccessedInContext", "CanChangeProtectedState",
		"CanNonSpaceWrap", "CanPropagateMouseClicks", "CanPropagateMouseMotion", "CanWordWrap",
		"ClearAllPoints", "ClearAlphaGradient", "ClearParentKey", "ClearPoint", "ClearPointsOffset",
		"ClearScripts", "ClearText", "CollapsesLayout", "CreateAnimationGroup", "EnableMouse",
		"EnableMouseMotion", "EnableMouseWheel", "FindCharacterIndexAtCoordinate", "FocusEnter",
		"FocusExit", "GetAccessRestrictions", "GetAlpha", "GetAlphaGradient", "GetAnimationGroups",
		"GetBottom", "GetCenter", "GetDebugName", "GetDrawLayer", "GetEffectiveScale", "GetFieldSize",
		"GetFont", "GetFontHeight", "GetFontObject", "GetForbiddenAspects", "GetHeight",
		"GetIndentedWordWrap", "GetInheritableForbiddenAspects", "GetJustifyH", "GetJustifyV", "GetLeft",
		"GetLineHeight", "GetMaxLines", "GetName", "GetNumLines", "GetNumPoints", "GetObjectTable",
		"GetObjectType", "GetParent", "GetParentKey", "GetPoint", "GetPointByName", "GetRect",
		"GetRight", "GetRotation", "GetRoundLayoutToNearestPixel", "GetScale", "GetScaleAnimationMode",
		"GetScaledRect", "GetScript", "GetShadowColor", "GetShadowOffset", "GetSize", "GetSmoothScaling",
		"GetSourceLocation", "GetSpacing", "GetStringHeight", "GetStringWidth", "GetText",
		"GetTextColor", "GetTextScale", "GetTop", "GetUnboundedStringWidth",
		"GetUnboundedStringWidthForText", "GetVertexColor", "GetWidth", "GetWrappedWidth",
		"HasAccessConstraints", "HasAnyAccessRestrictions", "HasAnyForbiddenAspects",
		"HasAnySecretAspect", "HasScript", "HasSecretAspect", "HasSecretValues", "Hide", "HookScript",
		"Intersects", "IsAnchoringRestricted", "IsAnchoringSecret", "IsCollapsed", "IsDragging",
		"IsForbidden", "IsIgnoringParentAlpha", "IsIgnoringParentScale", "IsMouseClickEnabled",
		"IsMouseEnabled", "IsMouseMotionEnabled", "IsMouseMotionFocus", "IsMouseOver",
		"IsMouseWheelEnabled", "IsObjectLoaded", "IsObjectType", "IsPreventingSecretValues",
		"IsProtected", "IsRectValid", "IsShown", "IsTruncated", "IsVisible", "MouseDown", "MouseUp",
		"OnColorsUpdated", "SetAllPoints", "SetAlpha", "SetAlphaFromBoolean", "SetAlphaGradient",
		"SetCollapsesLayout", "SetDesaturateEmbeddedTextures", "SetDrawLayer", "SetFixedColor",
		"SetFont", "SetFontHeight", "SetFontObject", "SetForbidden", "SetFormattedText", "SetHeight",
		"SetIgnoreParentAlpha", "SetIgnoreParentScale", "SetIndentedWordWrap", "SetJustifyH",
		"SetJustifyV", "SetMaxLines", "SetMouseClickEnabled", "SetMouseMotionEnabled", "SetNonSpaceWrap",
		"SetParent", "SetParentKey", "SetPassThroughButtons", "SetPoint", "SetPointsOffset",
		"SetPropagateMouseClicks", "SetPropagateMouseMotion", "SetRotation",
		"SetRoundLayoutToNearestPixel", "SetScale", "SetScaleAnimationMode", "SetScript",
		"SetShadowColor", "SetShadowOffset", "SetShown", "SetSize", "SetSmoothScaling", "SetSpacing",
		"SetText", "SetTextColor", "SetTextHeight", "SetTextScale", "SetTextToFit", "SetToDefaults",
		"SetVertexColor", "SetVertexColorFromBoolean", "SetWidth", "SetWordWrap",
		"ShouldButtonPassThrough", "Show", "StopAnimating",
	},
	Line = {
		"AddAccessRestrictions", "AddForbiddenAspects", "AddSecretAspect", "AdjustPointsOffset",
		"CanBeAccessedInContext", "CanChangeProtectedState", "CanPropagateMouseClicks",
		"CanPropagateMouseMotion", "ClearAllPoints", "ClearParentKey", "ClearPoint", "ClearPointsOffset",
		"ClearRadialProgressBar", "ClearSVG", "ClearScripts", "ClearTextureSlice", "ClearVertexOffsets",
		"CollapsesLayout", "CreateAnimationGroup", "EnableMouse", "EnableMouseMotion",
		"EnableMouseWheel", "FocusEnter", "FocusExit", "GetAccessRestrictions", "GetAlpha",
		"GetAnimationGroups", "GetAtlas", "GetBlendMode", "GetBottom", "GetCenter", "GetDebugName",
		"GetDesaturation", "GetDrawLayer", "GetEffectiveScale", "GetEndPoint", "GetForbiddenAspects",
		"GetHeight", "GetHitRectThickness", "GetHorizTile", "GetInheritableForbiddenAspects", "GetLeft",
		"GetName", "GetNumPoints", "GetObjectTable", "GetObjectType", "GetParent", "GetParentKey",
		"GetPoint", "GetPointByName", "GetRadialProgressBarEndOffset", "GetRadialProgressBarFeather",
		"GetRadialProgressBarPercent", "GetRadialProgressBarReverse", "GetRadialProgressBarStartOffset",
		"GetRect", "GetRight", "GetRotation", "GetRoundLayoutToNearestPixel", "GetScale",
		"GetScaledRect", "GetScript", "GetSize", "GetSourceLocation", "GetStartPoint", "GetTexCoord",
		"GetTexelSnappingBias", "GetTexture", "GetTextureFileID", "GetTextureFilePath",
		"GetTextureSliceMargins", "GetTextureSliceMode", "GetThickness", "GetTop", "GetVertTile",
		"GetVertexColor", "GetVertexOffset", "GetWidth", "HasAccessConstraints",
		"HasAnyAccessRestrictions", "HasAnyForbiddenAspects", "HasAnySecretAspect", "HasScript",
		"HasSecretAspect", "HasSecretValues", "Hide", "HookScript", "Intersects",
		"IsAnchoringRestricted", "IsAnchoringSecret", "IsBlockingLoadRequested", "IsCollapsed",
		"IsDesaturated", "IsDragging", "IsForbidden", "IsIgnoringParentAlpha", "IsIgnoringParentScale",
		"IsMouseClickEnabled", "IsMouseEnabled", "IsMouseMotionEnabled", "IsMouseMotionFocus",
		"IsMouseOver", "IsMouseWheelEnabled", "IsObjectLoaded", "IsObjectType",
		"IsPreventingSecretValues", "IsProtected", "IsRectValid", "IsShown", "IsSnappingToPixelGrid",
		"IsVisible", "MouseDown", "MouseUp", "ResetTexCoord", "SetAllPoints", "SetAlpha",
		"SetAlphaFromBoolean", "SetAtlas", "SetBlendMode", "SetBlockingLoadsRequested",
		"SetCollapsesLayout", "SetColorTexture", "SetDesaturated", "SetDesaturation", "SetDrawLayer",
		"SetEndPoint", "SetForbidden", "SetGradient", "SetHeight", "SetHitRectThickness", "SetHorizTile",
		"SetIgnoreParentAlpha", "SetIgnoreParentScale", "SetMask", "SetMouseClickEnabled",
		"SetMouseMotionEnabled", "SetParent", "SetParentKey", "SetPassThroughButtons", "SetPoint",
		"SetPointsOffset", "SetPropagateMouseClicks", "SetPropagateMouseMotion",
		"SetRadialProgressBarEndOffset", "SetRadialProgressBarFeather", "SetRadialProgressBarPercent",
		"SetRadialProgressBarReverse", "SetRadialProgressBarStartOffset", "SetRotation",
		"SetRoundLayoutToNearestPixel", "SetSVG", "SetScale", "SetScript", "SetShown", "SetSize",
		"SetSnapToPixelGrid", "SetSpriteSheetCell", "SetStartPoint", "SetTexCoord",
		"SetTexelSnappingBias", "SetTexture", "SetTextureSliceMargins", "SetTextureSliceMode",
		"SetThickness", "SetToDefaults", "SetVertTile", "SetVertexColor", "SetVertexColorFromBoolean",
		"SetVertexOffset", "SetWidth", "ShouldButtonPassThrough", "Show", "StopAnimating",
	},
	AnimationGroup = {
		"AddAccessRestrictions", "AddForbiddenAspects", "AddSecretAspect", "CanBeAccessedInContext",
		"ClearParentKey", "CreateAnimation", "Finish", "GetAccessRestrictions",
		"GetAnimationSpeedMultiplier", "GetAnimations", "GetDebugName", "GetDuration", "GetElapsed",
		"GetForbiddenAspects", "GetInheritableForbiddenAspects", "GetLoopState", "GetLooping", "GetName",
		"GetObjectTable", "GetObjectType", "GetParent", "GetParentKey", "GetProgress", "GetScript",
		"HasAccessConstraints", "HasAnyAccessRestrictions", "HasAnyForbiddenAspects",
		"HasAnySecretAspect", "HasScript", "HasSecretAspect", "HasSecretValues", "HookScript", "IsDone",
		"IsForbidden", "IsObjectType", "IsPaused", "IsPendingFinish", "IsPlaying",
		"IsPreventingSecretValues", "IsReverse", "IsSetToFinalAlpha", "Pause", "Play",
		"RemoveAnimations", "Restart", "SetAnimationSpeedMultiplier", "SetForbidden", "SetLooping",
		"SetParentKey", "SetPlaying", "SetScript", "SetToDefaults", "SetToFinalAlpha", "Stop",
	},
	Alpha = {
		"AddAccessRestrictions", "AddForbiddenAspects", "AddSecretAspect", "CanBeAccessedInContext",
		"ClearParentKey", "GetAccessRestrictions", "GetDebugName", "GetDuration", "GetElapsed",
		"GetEndDelay", "GetForbiddenAspects", "GetFromAlpha", "GetInheritableForbiddenAspects",
		"GetName", "GetObjectTable", "GetObjectType", "GetOrder", "GetParent", "GetParentKey",
		"GetProgress", "GetRegionParent", "GetScript", "GetSmoothProgress", "GetSmoothing",
		"GetStartDelay", "GetTarget", "GetToAlpha", "HasAccessConstraints", "HasAnyAccessRestrictions",
		"HasAnyForbiddenAspects", "HasAnySecretAspect", "HasScript", "HasSecretAspect",
		"HasSecretValues", "HookScript", "IsDelaying", "IsDone", "IsForbidden", "IsObjectType",
		"IsPaused", "IsPlaying", "IsPreventingSecretValues", "IsStopped", "Pause", "Play", "Restart",
		"SetChildKey", "SetDuration", "SetEndDelay", "SetForbidden", "SetFromAlpha", "SetOrder",
		"SetParent", "SetParentKey", "SetPlaying", "SetScript", "SetSmoothProgress", "SetSmoothing",
		"SetStartDelay", "SetTarget", "SetTargetKey", "SetTargetName", "SetTargetParent", "SetToAlpha",
		"SetToDefaults", "Stop",
	},
}
